[package]
name = "nostr-faucet"
version = "0.1.0"
edition = "2021"
description = "Ask a signet miner for coins over Nostr"
license = "MIT"

[lib]
name = "nostr_faucet"
path = "src/lib.rs"

[[bin]]
name = "nostr-faucet"
path = "src/bin/nostr-faucet.rs"

[[bin]]
name = "nostr-faucet-client"
path = "src/bin/nostr-faucet-client.rs"

[dependencies]
nostr-sdk = { git = "https://github.com/dukeh3/nostr.git", rev = "9ac9adc2" }
nwc = { git = "https://github.com/dukeh3/nostr.git", rev = "9ac9adc2" }
bip321 = { git = "https://github.com/DarkWebDivingClub/bip321.git", rev = "fcd4864" }

tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
